name: CamerasTest
main: com.github.ponclure.securitycams.CamerasSandbox
version: ${project.version}
description: Security Cams in Minecraft
author: Ponclure
api-version: 1.15

commands:
  setcamera:
    description: Create a camera with the specified name
  usecamera:
    description: Use the camera with the specified name
  deletecamera:
    description: Delete a camera with the specified name
